### ISSUE TITLE
Compilation error (undefined reference)

### ISSUE THREAD

**Issue by amirulmenjeni** [ros-melodic-arch/ros-melodic-actionlib-tutorials#1] opened 2019-12-01 23:48 UTC
I got a compilation error when compiling this package:

```
[ 86%] Building CXX object CMakeFiles/fibonacci_class_client.dir/src/fibonacci_class_client.cpp.o
[ 88%] Linking CXX executable devel/lib/actionlib_tutorials/fibonacci_class_client
/usr/bin/ld: CMakeFiles/fibonacci_class_client.dir/src/fibonacci_class_client.cpp.o: undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/fibonacci_class_client.dir/build.make:101: devel/lib/actionlib_tutorials/fibonacci_class_client] Error 1
make[1]: *** [CMakeFiles/Makefile2:173: CMakeFiles/fibonacci_class_client.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: ros-melodic-actionlib-tutorials
```

This problem is similar to https://github.com/ros-melodic-arch/ros-melodic-turtle-actionlib/issues/1. The workaround is the same and worked for me.

**Comment by acxz** [comment] 2019-12-03 05:23
@jwhendy if you have time, can you attempt to reproduce this error, I have not been able to do so.

**Comment by jwhendy** [comment] 2019-12-04 03:10
I can't reproduce this. That linked problem on facebook is odd to me. It's not clear what he changed from the comment (line 21 no longer points to a CXX flag), but it would seem that [L42](https://github.com/facebook/Surround360/blob/master/surround360_render/CMakeLists.txt#L42) should already add `-pthread` for linux?

I really don't understand what this option should do. Has anything updated for you, or is this your first time building this package? I rebuilt ~2 weeks ago from complete scratch and didn't run into this.

**Comment by acxz** [comment] 2019-12-04 03:21
I remember way back that, this was there was a pthread issue that had to be patched for some packages. I am able to build this package just fine as well. Do not know why amirulmenjeni had to use the patch for it to work. Well since it doesn't fail for you I am going to go ahead and close this without patching it.

**Closed as completed** 2019-12-04 03:24 UTC
